apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
    type: LoadBalancer
    selector:
        app: nginix
        purpose: helm
    ports:    
    - protocols: TCP 
      port: 80 #service-port  
      targetport: {{ .Values.configmap.port }} #target-port 
      nodePort: {{ .Value.service.nodeport }}
        